//this will return all subscribers to the user
GET http://localhost:3000/subs
//get all data
###

GET http://localhost:3000/subs/5e323e890571cd261c180864
//get specific data
###

POST http://localhost:3000/subs
Content-Type: application/json

{
    "name": "new_user01",
    "subToChannel": "jre"
}
//add an object to database
###

DELETE http://localhost:3000/subs/5e3245558024d55cd437a008

###

PATCH  http://localhost:3000/subs/5e32461f8024d55cd437a009
Content-Type: application/json

{
    "name": "test",
    "subToChannel": "jre"
}
###