//this will return all subscribers to the user
GET http://localhost:3000/subs

###

GET http://localhost:3000/subs/5e31155399689063c0d19887

###

POST http://localhost:3000/subs
Content-Type: application/json

{
    "name": "new_user01",
    "subToChannel": "jre"
}

###

GET http://localhost:3000/subs:3145

###


DELETE  http://localhost:3000/subs/5e31155399689063c0d19887

###